/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eew.client;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

import java.net.URI;

public class EEWClient {
    URI uri;
    WebSocketClient webSocketClient;
    EEWEventListener eewEventListener;

    public EEWClient(URI uri) {
        this.uri = uri;
        webSocketClient = new WebSocketClient(this.uri) {
            @Override
            public void onOpen(ServerHandshake handshakedata) {

            }

            @Override
            public void onMessage(String message) {

                ObjectMapper mapper = new ObjectMapper();
                try {
                    JsonNode rootNode = mapper.readTree(message);
                    if (rootNode.get("result").get("message").asText().equals("データがありません")) {
                        System.out.println("No Data");
                    }else {
                        if (eewEventListener != null) {

                            EEWInfo info = new EEWInfo();

                            EEWInfo.Result result = new EEWInfo.Result();
                            result.setMessage(rootNode.get("result").get("message").asText());
                            result.setStatus(rootNode.get("result").get("status").asText());
                            result.setIs_auth(rootNode.get("result").get("is_auth").asBoolean());
                            info.setResult(result);

                            EEWInfo.Security security = new EEWInfo.Security();
                            security.setRealm(rootNode.get("security").get("realm").asText());
                            security.setHash(rootNode.get("security").get("hash").asText());
                            info.setSecurity(security);

                            info.setReport_time(rootNode.get("report_time").asText());
                            info.setRegion_code(rootNode.get("region_code").asText());
                            info.setRequest_time(rootNode.get("request_time").asText());
                            info.setRegion_name(rootNode.get("region_name").asText());
                            info.setLongitude(rootNode.get("longitude").asText());
                            info.setIs_cancel(rootNode.get("is_cancel").asBoolean());
                            info.setDepth(rootNode.get("depth").asText());
                            info.setCalcintensity(rootNode.get("calcintensity").asText());
                            info.setIs_final(rootNode.get("is_final").asBoolean());
                            info.setIs_training(rootNode.get("is_training").asBoolean());
                            info.setLatitude(rootNode.get("latitude").asText());
                            info.setOrigin_time(rootNode.get("origin_time").asText());
                            info.setMagunitude(rootNode.get("magunitude").asText());
                            info.setReport_num(rootNode.get("report_num").asText());
                            info.setRequest_hypo_type(rootNode.get("request_hypo_type").asText());
                            info.setReport_id(rootNode.get("report_id").asText());
                            info.setAlertflg(rootNode.get("alertflg").asText());

                            eewEventListener.happen(info);
                        }
                    }

                } catch (JsonProcessingException e) {
                    e.printStackTrace();
                }

//                JsonObject rootObject = new Gson().fromJson(message, JsonObject.class);
//                if (rootObject.get("result").getAsJsonObject().get("message").getAsString().equals("データがありません")) {
//                    System.out.println("NoData");
//                }else {
//                    if (eewEventListener != null){
//                        EEWInfo info = new EEWInfo();
//
//                        EEWInfo.Result result = new EEWInfo.Result();
//                        result.setMessage(rootObject.get("result").getAsJsonObject().get("message").getAsString());
//                        result.setStatus(rootObject.get("result").getAsJsonObject().get("status").getAsString());
//                        result.setIs_auth(rootObject.get("result").getAsJsonObject().get("is_auth").getAsBoolean());
//                        info.setResult(result);
//
//                        EEWInfo.Security security = new EEWInfo.Security();
//                        security.setRealm(rootObject.get("security").getAsJsonObject().get("realm").getAsString());
//                        security.setHash(rootObject.get("security").getAsJsonObject().get("hash").getAsString());
//                        info.setSecurity(security);
//
//                        info.setReport_time(rootObject.get("report_time").getAsString());
//                        info.setRegion_code(rootObject.get("region_code").getAsString());
//                        info.setRequest_time(rootObject.get("request_time").getAsString());
//                        info.setRegion_name(rootObject.get("region_name").getAsString());
//
//                        info.setLongitude(rootObject.get("longitude").getAsString());
//                        info.setIs_cancel(rootObject.get("is_cancel").getAsBoolean());
//                        info.setDepth(rootObject.get("depth").getAsString());
//                        info.setCalcintensity(rootObject.get("calcintensity").getAsString());
//                        info.setIs_final(rootObject.get("is_final").getAsBoolean());
//                        info.setIs_training(rootObject.get("is_training").getAsBoolean());
//                        info.setLatitude(rootObject.get("latitude").getAsString());
//                        info.setOrigin_time(rootObject.get("origin_time").getAsString());
//                        info.setMagunitude(rootObject.get("magunitude").getAsString());
//                        info.setReport_num(rootObject.get("report_num").getAsString());
//                        info.setRequest_hypo_type(rootObject.get("request_hypo_type").getAsString());
//                        info.setReport_id(rootObject.get("report_id").getAsString());
//                        info.setAlertflg(rootObject.get("alertflg").getAsString());
//
//                        eewEventListener.happen(info);
//                    }
//                    System.out.println("Data Found!");
//                }
//                eewEventListener.happen(message);
            }

            @Override
            public void onClose(int code, String reason, boolean remote) {

            }

            @Override
            public void onError(Exception ex) {

            }
        };
    }

    public void setEewEventListener(EEWEventListener eewEventListener) {
        this.eewEventListener = eewEventListener;
    }

    public void start() {
        webSocketClient.connect();
    }

    public void exit() {
        webSocketClient.close();
    }
}
